server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    resolver 169.254.169.254 valid=10s;

    location /api/ {
        proxy_pass $BACKEND_URL/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
